# Generated by Django 6.0.3 on 2026-06-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.user')),
            ],
        ),
        migrations.CreateModel(
            name='Courseprogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.lesson')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.enrollment')),
            ],
        ),
    ]
